version : '3.8'

services:
  postgres : 
    image : postgres
    ports : 
      - "5432:5432"
    environment :
      DB_NAME : postgres
      DB_PASSWORD : postgres
      DB_USER : postgres

  redis : 
    image : redis
    ports : 
      - "6379:6379"
    environment :
      redis_env : redis_env_value
